apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: guestbook-ab-test-a

images:
- name: ghcr.io/jessesuen/guestbook
  newName: ghcr.io/jessesuen/guestbook
  newTag: v0.0.1
